# Generated by Django 5.0.7 on 2024-07-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firtname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Titlename', models.CharField(max_length=50)),
                ('Haspassport', models.BooleanField()),
                ('Salary', models.IntegerField()),
                ('Birthdate', models.DateField()),
                ('Hiredate', models.DateField()),
                ('Notes', models.CharField(max_length=200)),
                ('Country', models.CharField(choices=[('TH', 'THAILAND'), ('IND', 'INDIA'), ('USA', 'United States of America'), ('UK', 'United Kingdom'), ('AUS', 'AUSTRALIA'), ('AU', 'AUSTRIA'), ('SP', 'SPAIN')], default=None, max_length=50)),
            ],
        ),
    ]
