# Generated by Django 5.0.7 on 2024-07-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Email',
            field=models.EmailField(default='', max_length=60),
        ),
    ]
