# Generated by Django 5.0.7 on 2024-07-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Phonenumber',
            field=models.CharField(default='', max_length=20),
        ),
    ]
